/* GENERATED by tools/build-school-map.js from the hand sketch. Do not hand-edit - re-run the builder. */
var SCANPOINTS = (function () {
  var LIST = [
    { id: "ME", node: "entrance", level: "G", audience: "foot",
      label: "Main Entrance",
      mount: "Inside the entrance door, at eye level.", rev: 1 },

    { id: "RC", node: "recep", level: "G", audience: "foot",
      label: "Reception 2",
      mount: "On the reception counter.", rev: 1 },

    { id: "CF", node: "caf", level: "G", audience: "foot",
      label: "Cafeteria",
      mount: "Beside the cafeteria door.", rev: 1 },

    { id: "LB", node: "lib-door", level: "G", audience: "foot",
      label: "Library Entrance",
      mount: "On the library door frame.", rev: 1 },

    { id: "AM", node: "amph", level: "G", audience: "foot",
      label: "Amphitheatre",
      mount: "On the post at the top of the steps.", rev: 1 },

    { id: "PL", node: "plc", level: "G", audience: "foot",
      label: "PLC",
      mount: "Beside the PLC door.", rev: 1 },

    { id: "SR", node: "staff", level: "G", audience: "foot",
      label: "Staffroom",
      mount: "Beside the staffroom door.", rev: 1 },

    { id: "MR", node: "meet", level: "G", audience: "foot",
      label: "Meeting Room",
      mount: "Beside the meeting room door.", rev: 1 },

    { id: "KV", node: "kanvas", level: "G", audience: "foot",
      label: "Kanvas Studio",
      mount: "Beside the studio door.", rev: 1 },

    { id: "KK", node: "kukoos", level: "G", audience: "foot",
      label: "Kukoos Studio",
      mount: "Beside the studio door.", rev: 1 },

    { id: "MH", node: "hive1", level: "G", audience: "foot",
      label: "Maker's Hive-1",
      mount: "Beside the Maker's Hive-1 door.", rev: 1 },

    { id: "CR", node: "conf", level: "G", audience: "foot",
      label: "Conference Room",
      mount: "Beside the conference room door.", rev: 1 },

    { id: "TC", node: "teach", level: "G", audience: "foot",
      label: "Teacher's Cubicle",
      mount: "On the cubicle partition.", rev: 1 },

    { id: "SS", node: "stairs-s", level: "G", audience: "foot",
      label: "Stairs opposite Reception",
      mount: "At the foot of the stairs.", rev: 1 },

    { id: "SN", node: "stairs-ne", level: "G", audience: "foot",
      label: "Cafeteria Stairs",
      mount: "At the foot of the stairs, in the lobby behind Reception 2.", rev: 1 }
  ];

  var RETIRED = [];

  var BY_ID = {};
  LIST.forEach(function (s) { BY_ID[s.id.toUpperCase()] = s; });

  return {
    all: LIST,
    retired: RETIRED,
    byId: function (id) { return BY_ID[String(id || '').toUpperCase()] || null; },
    byNode: function (n) {
      for (var i = 0; i < LIST.length; i++) if (LIST[i].node === n) return LIST[i];
      return null;
    },
    url: function (base, id) { return base.replace(/[/]+$/, '') + '/?s=' + id; }
  };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = SCANPOINTS;
