/* GENERATED by tools/build-school-map.js from the hand sketch. Do not hand-edit - re-run the builder. */
var SCANPOINTS = (function () {
  var LIST = [
    { id: "RC", node: "recep", level: "F1", audience: "foot",
      label: "Reception 2",
      mount: "On the reception counter.", rev: 1 },

    { id: "CF", node: "caf", level: "F1", audience: "foot",
      label: "Cafeteria",
      mount: "Beside the cafeteria door.", rev: 1 },

    { id: "LB", node: "lib-door", level: "F1", audience: "foot",
      label: "Library Entrance",
      mount: "On the library door frame.", rev: 1 },

    { id: "AM", node: "amph", level: "F1", audience: "foot",
      label: "Amphitheatre",
      mount: "On the post at the top of the steps.", rev: 1 },

    { id: "PL", node: "plc", level: "F1", audience: "foot",
      label: "PLC",
      mount: "Beside the PLC door.", rev: 1 },

    { id: "SR", node: "staff", level: "F1", audience: "foot",
      label: "Staffroom",
      mount: "Beside the staffroom door.", rev: 1 },

    { id: "MR", node: "meet", level: "F1", audience: "foot",
      label: "Meeting Room",
      mount: "Beside the meeting room door.", rev: 1 },

    { id: "KV", node: "kanvas", level: "F1", audience: "foot",
      label: "Kanvas Studio",
      mount: "Beside the studio door.", rev: 1 },

    { id: "KK", node: "kukoos", level: "F1", audience: "foot",
      label: "Kukoos Studio",
      mount: "Beside the studio door.", rev: 1 },

    { id: "MH", node: "hive1", level: "F1", audience: "foot",
      label: "Maker's Hive-1",
      mount: "Beside the Maker's Hive-1 door.", rev: 1 },

    { id: "CR", node: "conf", level: "F1", audience: "foot",
      label: "Conference Room",
      mount: "Beside the conference room door.", rev: 1 },

    { id: "TC", node: "teach", level: "F1", audience: "foot",
      label: "Teacher's Cubicle",
      mount: "On the cubicle partition.", rev: 1 },

    { id: "SS", node: "stairs-s", level: "F1", audience: "foot",
      label: "Stairs opposite Reception",
      mount: "At the foot of the stairs.", rev: 1 },

    { id: "SN", node: "stairs-ne", level: "F1", audience: "foot",
      label: "Cafeteria Stairs",
      mount: "At the foot of the stairs, in the lobby behind Reception 2.", rev: 1 },

    { id: "GA", node: "gallery", level: "F1", audience: "foot",
      label: "Gallery Area",
      mount: "On the wall at the corridor end of the rock garden.", rev: 1 },

    { id: "MG", node: "g-gate", level: "G", audience: "foot",
      label: "Main Gate",
      mount: "On the gatepost, inside the gate.", rev: 1 },

    { id: "R1", node: "g-recep", level: "G", audience: "foot",
      label: "Reception",
      mount: "On the reception counter.", rev: 1 },

    { id: "IN", node: "infirmary", level: "G", audience: "foot",
      label: "Infirmary",
      mount: "Beside the infirmary door.", rev: 1 },

    { id: "FF", node: "field", level: "G", audience: "foot",
      label: "Football Field",
      mount: "On the post at the field entrance.", rev: 1 },

    { id: "EY", node: "eyp", level: "G", audience: "foot",
      label: "EYP Atelier",
      mount: "Beside the atelier door.", rev: 1 },

    { id: "FS", node: "ffs", level: "G", audience: "foot",
      label: "First Floor Stairs",
      mount: "At the foot of the stairs.", rev: 1 },

    { id: "LF", node: "lift", level: "G", audience: "foot",
      label: "Lift",
      mount: "Beside the lift door, in the corridor.", rev: 1 },

    { id: "CS", node: "cs", level: "G", audience: "foot",
      label: "Cafeteria Stairs (ground)",
      mount: "At the foot of the stairs.", rev: 1 }
  ];

  var RETIRED = [];

  var BY_ID = {};
  LIST.forEach(function (s) { BY_ID[s.id.toUpperCase()] = s; });

  return {
    all: LIST,
    retired: RETIRED,
    byId: function (id) { return BY_ID[String(id || '').toUpperCase()] || null; },
    byNode: function (n) {
      for (var i = 0; i < LIST.length; i++) if (LIST[i].node === n) return LIST[i];
      return null;
    },
    url: function (base, id) { return base.replace(/[/]+$/, '') + '/?s=' + id; }
  };
})();

if (typeof module !== 'undefined' && module.exports) module.exports = SCANPOINTS;
